name: ci

on:
  schedule:
    - cron: '0 10 * * *'
  push:
    branches:
      - 'master'
      - 'releases/v*'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'master'
      - 'releases/v*'

jobs:
  image:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image:
          - alpine:3.9
          - alpine:latest
          - moby/buildkit:master
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Scan for vulnerabilities
        id: scan
        uses: ./
        with:
          image: ${{ matrix.image }}
      -
        name: JSON result
        run: cat ${{ steps.scan.outputs.json }}

  tarball:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build
        uses: docker/build-push-action@v2
        with:
          context: ./test
          outputs: type=oci,dest=/tmp/image.tar
          tags: name/app:latest
      -
        name: Scan for vulnerabilities
        id: scan
        uses: ./
        with:
          tarball: /tmp/image.tar
      -
        name: JSON result
        run: cat ${{ steps.scan.outputs.json }}

  sarif:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build
        uses: docker/build-push-action@v2
        with:
          context: ./test
          outputs: type=oci,dest=/tmp/image.tar
          tags: name/app:latest
      -
        name: Scan for vulnerabilities
        id: scan
        uses: ./
        with:
          tarball: /tmp/image.tar
          dockerfile: ./test/Dockerfile
      -
        name: SARIF result
        run: cat ${{ steps.scan.outputs.sarif }}

  annotations:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image:
          - alpine:3.9
          - alpine:latest
          - moby/buildkit:master
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Scan for vulnerabilities
        uses: ./
        with:
          image: ${{ matrix.image }}
          annotations: true

  threshold:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image:
          - alpine:3.9
          - alpine:3.10
          - alpine:latest
          - moby/buildkit:master
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Scan for vulnerabilities
        continue-on-error: true
        uses: ./
        with:
          image: ${{ matrix.image }}
          severity_threshold: HIGH

  build-scan-push:
    runs-on: ubuntu-latest
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    env:
      REPO_SLUG: localhost:5000/name/app
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REPO_SLUG }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver-opts: network=host
      -
        name: Build and load
        uses: docker/build-push-action@v2
        with:
          context: ./test
          file: ./test/Dockerfile
          load: true
          tags: ${{ steps.meta.outputs.tags }}
      -
        name: Scan for vulnerabilities
        uses: ./
        with:
          image: ${{ env.REPO_SLUG }}:${{ steps.meta.outputs.version }}
          dockerfile: ./test/Dockerfile
      -
        name: Build multi-platform and push
        uses: docker/build-push-action@v2
        with:
          context: ./test
          file: ./test/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
