name: scan

on:
  workflow_dispatch:
    inputs:
      image:
        description: 'Image to scan'
        required: true

jobs:
  image:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Scan for vulnerabilities
        id: scan
        uses: ./
        with:
          image: ${{ github.event.inputs.image }}
          annotations: true
      -
        name: JSON result
        run: cat ${{ steps.scan.outputs.json }}
