name: trivy-releases-json

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */12 * * *'
  push:
    branches:
      - 'master'
  pull_request:

jobs:
  generate:
    uses: crazy-max/.github/.github/workflows/releases-json.yml@fa6141aedf23596fb8bdcceab9cce8dadaa31bd9
    with:
      repository: aquasecurity/trivy
      artifact_name: trivy-releases-json
      filename: trivy-releases.json
    secrets: inherit

  open-pr:
    runs-on: ubuntu-22.04
    if: github.event_name != 'pull_request'
    needs:
      - generate
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Download
        uses: actions/download-artifact@v4
        with:
          name: trivy-releases-json
          path: .github
      -
        name: Commit changes
        run: |
          git add -A .
      -
        name: Create PR
        uses: peter-evans/create-pull-request@4320041ed380b20e97d388d56a7fb4f9b8c20e79
        with:
          base: master
          branch: bot/trivy-releases-json
          commit-message: "update .github/trivy-releases.json"
          signoff: true
          delete-branch: true
          title: "Update `.github/trivy-releases.json`"
          body: |
            Update `.github/trivy-releases.json` to keep in sync with [https://github.com/aquasecurity/trivy](https://github.com/aquasecurity/trivy).
          draft: false
